#!/usr/bin/env python3
# ---------------------------------------------------------------------------
# gen_kat_vectors.py -- emit src/mldsa_kat_vectors.ads from the authoritative
# ML-DSA-65 sigVer KAT file kat/mldsa65_sigver.json.
#
# The JSON is the external/pure ACVP-shaped sigVer fixture (parameterSet
# "ML-DSA-65", interface "external", preHash "pure"), 15 tests, tcId 31..45,
# 3 expected=true / 12 expected=false. Each test carries:
#   pk        (1952-byte hex public key)
#   message   (hex)
#   context   (hex)
#   signature (3309-byte hex signature)
#   expected  (bool)
#
# We DO NOT invent any vector: every byte comes straight from the JSON. The
# generated .ads exposes one fully-constrained constant V31..V45 per test plus
# a Count constant. Each record carries its own Msg_Len / Ctx_Len discriminants
# so every vector is self-describing.
#
# Run from lthing-spark/:  python3 tools/gen_kat_vectors.py
# GPL-3.0-or-later.
# ---------------------------------------------------------------------------

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                       # lthing-spark/
JSON_PATH = os.path.join(ROOT, "kat", "mldsa65_sigver.json")
OUT_PATH = os.path.join(ROOT, "src", "mldsa_kat_vectors.ads")

PK_BYTES = 1952
SIG_BYTES = 3309


def hex_to_bytes(h):
    if h is None:
        return b""
    return bytes.fromhex(h)


def fmt_array(data, indent):
    """Render a byte string as an Ada positional aggregate body of 16#..#
    values (one or more elements -- caller guarantees len >= 2)."""
    pad = " " * indent
    items = ["16#%02X#" % b for b in data]
    lines = []
    per_line = 12
    for i in range(0, len(items), per_line):
        chunk = ", ".join(items[i:i + per_line])
        lines.append(pad + chunk)
    return ",\n".join(lines)


def fmt_var_array(name_field, data, base_indent):
    """Render a variable-length 1-based Byte_Array component (Msg / Ctx).
    Handles the awkward Ada cases: an empty (null-range) array becomes
    (others => 0), a single element becomes a named association (Ada forbids
    a one-element positional aggregate), >=2 elements use positional form."""
    pad = " " * base_indent
    field = "%s%-8s =>" % (pad, name_field)
    if len(data) == 0:
        return field + "\n%s  (others => 0)" % pad
    if len(data) == 1:
        return field + "\n%s  (1 => 16#%02X#)" % (pad, data[0])
    out = [field, "%s  (" % pad, fmt_array(data, base_indent + 3),
           "%s  )" % pad]
    return "\n".join(out)


def emit_vector(name, v):
    pk = hex_to_bytes(v["pk"])
    sig = hex_to_bytes(v["signature"])
    msg = hex_to_bytes(v.get("message"))
    ctx = hex_to_bytes(v.get("context"))
    assert len(pk) == PK_BYTES, "%s pk len %d" % (name, len(pk))
    assert len(sig) == SIG_BYTES, "%s sig len %d" % (name, len(sig))
    expected = bool(v["expected"])

    msg_len = len(msg)
    ctx_len = len(ctx)

    out = []
    out.append("   %s : constant Vector (Msg_Len => %d, Ctx_Len => %d) :="
               % (name, msg_len, ctx_len))
    out.append("     (Msg_Len  => %d," % msg_len)
    out.append("      Ctx_Len  => %d," % ctx_len)
    out.append("      Expected => %s," % ("True" if expected else "False"))
    out.append("      PK       =>")
    out.append("        (")
    out.append(fmt_array(pk, 9))
    out.append("        ),")
    out.append("      Sig      =>")
    out.append("        (")
    out.append(fmt_array(sig, 9))
    out.append("        ),")

    # Msg and Ctx are 1-based variable-length components and are always
    # supplied (empty ones render as (others => 0)).
    out.append(fmt_var_array("Msg", msg, 6) + ",")
    out.append(fmt_var_array("Ctx", ctx, 6) + ");")
    return "\n".join(out)


def main():
    with open(JSON_PATH) as f:
        data = json.load(f)

    tests = sorted(data["tests"], key=lambda t: t["tcId"])

    header = []
    bar = "-" * 78
    header.append(bar)
    header.append("--  MLDSA_KAT_Vectors -- GENERATED by tools/gen_kat_vectors.py. DO NOT EDIT.")
    header.append("--")
    header.append("--  Source: kat/mldsa65_sigver.json")
    header.append("--    parameterSet=%s  interface=%s  preHash=%s"
                  % (data.get("parameterSet"), data.get("interface"),
                     data.get("preHash")))
    header.append("--    %d ML-DSA-65 sigVer vectors, tcId %d..%d."
                  % (len(tests), tests[0]["tcId"], tests[-1]["tcId"]))
    n_true = sum(1 for t in tests if t["expected"])
    header.append("--    Expected outcomes: %d accept / %d reject."
                  % (n_true, len(tests) - n_true))
    header.append("--")
    header.append("--  Every byte is copied verbatim from the authoritative fixture; no value")
    header.append("--  is hand-invented. Regenerate with: python3 tools/gen_kat_vectors.py")
    header.append("--  GPL-3.0-or-later.")
    header.append(bar)
    header.append("")
    header.append("pragma Style_Checks (Off);")
    header.append("")
    header.append("with LTHING_Types; use LTHING_Types;")
    header.append("")
    header.append("package MLDSA_KAT_Vectors is")
    header.append("")
    header.append("   --  A self-describing sigVer KAT vector. Msg_Len / Ctx_Len discriminants")
    header.append("   --  size the variable-length Msg and Ctx components.")
    header.append("   type Vector (Msg_Len, Ctx_Len : Natural) is record")
    header.append("      PK       : Byte_Array (0 .. %d);" % (PK_BYTES - 1))
    header.append("      Sig      : Byte_Array (0 .. %d);" % (SIG_BYTES - 1))
    header.append("      --  1-based ranges: a discriminant constraint may not be an")
    header.append("      --  expression (no \"Msg_Len - 1\"), so the index runs 1 .. Len.")
    header.append("      Msg      : Byte_Array (1 .. Msg_Len);")
    header.append("      Ctx      : Byte_Array (1 .. Ctx_Len);")
    header.append("      Expected : Boolean;")
    header.append("   end record;")
    header.append("")
    header.append("   Count : constant := %d;" % len(tests))
    header.append("")

    body = []
    names = []
    for t in tests:
        name = "V%d" % t["tcId"]
        names.append(name)
        body.append(emit_vector(name, t))
        body.append("")

    footer = ["end MLDSA_KAT_Vectors;", ""]

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(header) + "\n")
        f.write("\n".join(body) + "\n")
        f.write("\n".join(footer))

    print("wrote %s (%d vectors: %s)"
          % (OUT_PATH, len(tests), ", ".join(names)))


if __name__ == "__main__":
    main()
