#!/usr/bin/env python3
"""Emit src/mldsa87_kat_vectors.ads verbatim from kat/mldsa87_sigver.json.

Mirror of the ML-DSA-65 generator (tools/gen_kat_vectors.py), sized to the
ML-DSA-87 parameter set: PK = 2592 B, Sig = 4627 B. Every byte is copied
from the authoritative NIST ACVP fixture; no value is hand-invented. The
emitted package is pure data (no SPARK proof obligations).

Run from lthing-spark/:  python3 tools/gen_mldsa87_kat_vectors.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)                       # lthing-spark/
SRC = os.path.join(ROOT, "kat", "mldsa87_sigver.json")
OUT = os.path.join(ROOT, "src", "mldsa87_kat_vectors.ads")

PK_LAST = 2591    # 2592-byte ML-DSA-87 public key
SIG_LAST = 4626   # 4627-byte ML-DSA-87 signature


def emit_array(hexstr, first):
    """Render a Byte_Array aggregate. first = lower bound (0 for PK/Sig,
    1 for the 1-based Msg/Ctx components)."""
    b = bytes.fromhex(hexstr)
    if len(b) == 0:
        return "(others => 0)"
    if len(b) == 1:
        return "(%d => 16#%02X#)" % (first, b[0])
    rows = []
    for i in range(0, len(b), 12):
        chunk = b[i:i + 12]
        sep = "" if i + 12 >= len(b) else ","
        rows.append("         " + ", ".join("16#%02X#" % x for x in chunk) + sep)
    return "(\n" + "\n".join(rows) + "\n        )"


def main():
    d = json.load(open(SRC))
    tests = d["tests"]
    assert d["parameterSet"] == "ML-DSA-87", d["parameterSet"]
    for t in tests:
        assert len(bytes.fromhex(t["pk"])) == PK_LAST + 1, t["tcId"]
        assert len(bytes.fromhex(t["signature"])) == SIG_LAST + 1, t["tcId"]

    out = []
    w = out.append
    w("-" * 78)
    w("--  MLDSA87_KAT_Vectors -- GENERATED by tools/gen_mldsa87_kat_vectors.py.")
    w("--  DO NOT EDIT.")
    w("--")
    w("--  Source: kat/mldsa87_sigver.json")
    w("--    parameterSet=ML-DSA-87  interface=external  preHash=pure")
    w("--    %d ML-DSA-87 sigVer vectors, tcId %d..%d."
      % (len(tests), tests[0]["tcId"], tests[-1]["tcId"]))
    acc = sum(1 for t in tests if t["expected"])
    w("--    Expected outcomes: %d accept / %d reject." % (acc, len(tests) - acc))
    w("--")
    w("--  Every byte is copied verbatim from the authoritative NIST ACVP")
    w("--  fixture; no value is hand-invented. Provenance: the ML-DSA-65 group")
    w("--  of the same ACVP file matches kat/mldsa65_sigver.json byte-for-byte.")
    w("--  GPL-3.0-or-later.")
    w("-" * 78)
    w("")
    w("pragma Style_Checks (Off);")
    w("")
    w("with LTHING_Types; use LTHING_Types;")
    w("")
    w("package MLDSA87_KAT_Vectors is")
    w("")
    w("   --  A self-describing sigVer KAT vector. Msg_Len / Ctx_Len discriminants")
    w("   --  size the variable-length Msg and Ctx components.")
    w("   type Vector (Msg_Len, Ctx_Len : Natural) is record")
    w("      PK       : Byte_Array (0 .. %d);" % PK_LAST)
    w("      Sig      : Byte_Array (0 .. %d);" % SIG_LAST)
    w("      --  1-based ranges: a discriminant constraint may not be an")
    w('      --  expression (no "Msg_Len - 1"), so the index runs 1 .. Len.')
    w("      Msg      : Byte_Array (1 .. Msg_Len);")
    w("      Ctx      : Byte_Array (1 .. Ctx_Len);")
    w("      Expected : Boolean;")
    w("   end record;")
    w("")
    w("   Count : constant := %d;" % len(tests))
    w("")
    for t in tests:
        msg = bytes.fromhex(t["message"])
        ctx = bytes.fromhex(t["context"])
        w("   V%d : constant Vector (Msg_Len => %d, Ctx_Len => %d) :="
          % (t["tcId"], len(msg), len(ctx)))
        w("     (Msg_Len  => %d," % len(msg))
        w("      Ctx_Len  => %d," % len(ctx))
        w("      Expected => %s," % ("True" if t["expected"] else "False"))
        w("      PK       =>")
        w("        " + emit_array(t["pk"], 0) + ",")
        w("      Sig      =>")
        w("        " + emit_array(t["signature"], 0) + ",")
        w("      Msg      =>")
        w("        " + emit_array(t["message"], 1) + ",")
        w("      Ctx      =>")
        w("        " + emit_array(t["context"], 1) + ");")
        w("")
    w("end MLDSA87_KAT_Vectors;")

    open(OUT, "w").write("\n".join(out) + "\n")
    print("wrote %s (%d vectors, %d bytes)"
          % (OUT, len(tests), os.path.getsize(OUT)))


if __name__ == "__main__":
    main()
